# /etc/zsh/zshrc: system-wide .zshrc file for zsh(1).
#
# This file is sourced only for interactive shells. It
# should contain commands to set up aliases, functions,
# options, key bindings, etc.
#
# Global Order: zshenv, zprofile, zshrc, zlogin

zstyle ':completion:*:sudo:*' command-path /usr/local/sbin /usr/local/bin \
			     /usr/local/arm/bin /usr/sbin /usr/bin /sbin /bin /usr/X11R6/bin

#unalias run-help
autoload run-help

autoload -U compinit
compinit

# my stuff 
# PS1='%1c # '
PS1='%m@%1c # '

# shortcut remapping
stty intr ^K

# command aliases
alias la='ls -A'
alias l='ls -CF'
alias ll='ls -l'
alias lh='ls -lh'
alias cp='cp -r'
alias df='df -h'
alias rm='rm -r'
alias maek='make'
alias chown='chown -R'
alias chmod='chmod -R'
alias pyhton='python'
alias eenv='wokron'
alias xenv='deactivate'
alias newenv='mkvirtualenv'
alias indent='indent -npsl -bl -bli0 -bad -bap -bbb'

# data directory aliases
alias code='cd ~/code'
alias misc='cd ~/misc'

alias home='cd ~/'
alias downloads='cd ~/downloads'

# python virtualenv
export WORKON_HOME=~/.virtualenvs
source /usr/share/virtualenvwrapper/virtualenvwrapper.sh

#Ubuntu Launchpad
export DEBEMAIL="obulpathi@gmail.com"
export DEBFULLNAME="Obulapathi"

# display
set sw=4
set tab-width=4
setterm -regtabs 4

# Window title
case $TERM in
    rxvt|*term)
    # precmd() { print -Pn "%~\a" }
    # preexec () { print -Pn "\e]0;$1\a" }
    chpwd() { print -Pn "\e]2;%1d\a"}
    ;;
esac

echo "Life, Liberty and Pursiut of Open Standards."
