# /etc/zsh/zshrc: system-wide .zshrc file for zsh(1).
#
# This file is sourced only for interactive shells. It
# should contain commands to set up aliases, functions,
# options, key bindings, etc.
#
# Global Order: zshenv, zprofile, zshrc, zlogin

zstyle ':completion:*:sudo:*' command-path /usr/local/sbin /usr/local/bin \
			     /usr/local/arm/bin /usr/sbin /usr/bin /sbin /bin /usr/X11R6/bin

#unalias run-help
autoload run-help

autoload -U compinit
compinit

# my stuff 
# PS1='%1c # '
PS1='%m@%1c # '

# security 
# umask 077

# spelling options 
# setopt correctall
# alias mv='nocorrect mv'       # no spelling correction on mv
# alias rm='nocorrect rm'       # no spelling correction on mv
# alias cp='nocorrect cp'       # no spelling correction on cp
# alias mkdir='nocorrect mkdir' # no spelling correction on mkdir

# command aliases
alias la='ls -A'
alias l='ls -CF'
alias ll='ls -l'
alias lh='ls -lh'
alias cp='cp -r'
alias df='df -h'
alias rm='rm -r'
alias chown='chown -R'
alias chmod='chmod -R'
alias indent='indent -npsl -bl -bli0 -bad -bap -bbb'

# data directory aliases
alias code='cd ~/code'
alias misc='cd ~/misc'

alias home='cd ~/'
alias downloads='cd ~/downloads'

#Ubuntu Launchpad
export DEBEMAIL="obulpathi@gmail.com"
export DEBFULLNAME="Obulapathi"

# display
set sw=4
set tab-width=4
setterm -regtabs 4

echo "Life, Liberty and Pursiut of Open Standards."
